name: Deploying Shivam Baghla's Digital Home
run-name: ${{ github.actor }} pushed to master
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: "Action Details 🚀"
        run: |
          echo "
          Runner OS: ${{ runner.os }}
          Triggered Event: ${{ github.event_name }}
          Event By: ${{ github.actor }}
          Branch: ${{ github.ref }}
          Repo: ${{ github.repository }}
          "
      - name: Install Pandoc
        uses: pandoc/actions/setup@main
        with:
          version: 2.19
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: list all files
        run: ls -al
      - name: Build (Will convert all MDs to HTMLs)
        run: |
          mkdir -p docs
          rm -rf docs/*
          for i in $(find . -type f -name "*.md") ; do
            echo "$i"
            pandoc -s $i -o docs/$(basename $i .md).html --css=theme.css --self-contained
            rm $i
          done
      - name: list all files
        run: ls -al
      - name: Commit generated folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add docs
          git commit -m "Generate and deploy folder" --no-verify
      - name: Push changes
        run: |
          git push origin HEAD:master
      - run: echo "🍏 This job's status is ${{ job.status }}."