name: generate html from MDs under md directory
run-name: ${{ github.actor }} pushed to master
on: [push]
jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: "Action Details 🚀"
        run: |
          echo "
          Runner OS: ${{ runner.os }}
          Triggered Event: ${{ github.event_name }}
          Event By: ${{ github.actor }}
          Branch: ${{ github.ref }}
          Repo: ${{ github.repository }}
          "
      - name: Install Pandoc
        uses: pandoc/actions/setup@main
        with:
          version: 2.19
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: list all files
        run: ls -al
      - name: Build
        run: |
          mkdirs generated
          for i in ./md/*.md ; do echo "$i" && pandoc -s $i -o generated/$i.html ; done
      - name: list all files
        run: ls -al
      - name: Commit generated folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout -b deployment
          git add generated/
          git commit -m "Generate and deploy folder"
      
      - name: Push changes
        run: |
          git push origin deployment
      - run: echo "🍏 This job's status is ${{ job.status }}."